steps:
  - id: "deploy_function"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: bash
    args:
      - -c
      - |
        gcloud functions deploy ${_FUNCTIONS_NAME} \
          --region=${_REGION} \
          --source=src/ \
          --runtime=${_RUN_TIME} \
          --trigger-http \
          --project=my-project-1567934249798 \
          --service-account=${_SERVICE_ACCOUNT_FUNCTIONS} \
          --build-service-account=projects/${PROJECT_ID}/serviceAccounts/${_SERVICE_ACCOUNT_TRIGGER} \
          --allow-unauthenticated
          --entry-point=fetch_stock_financials \

substitutions:
  _FUNCTIONS_NAME: "fetch_stock_financials"
  _REGION: "us-central1"
  _SERVICE_ACCOUNT_FUNCTIONS: "sa-functions@my-project-1567934249798.iam.gserviceaccount.com"
  _SERVICE_ACCOUNT_TRIGGER: "sa-deploy@my-project-1567934249798.iam.gserviceaccount.com"
  _RUN_TIME: "python312"

logsBucket: "gs://finance_20250820"
serviceAccount: "projects/my-project-1567934249798/serviceAccounts/sa-build@my-project-1567934249798.iam.gserviceaccount.com"

options:
  logging: GCS_ONLY